# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [3]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data). 

Data Set Information:

This is perhaps the best known database to be found in the pattern recognition literature. Fisher's paper is a classic in the field and is referenced frequently to this day. (See Duda & Hart, for example.) The data set contains 3 classes of 50 instances each, where each class refers to a type of iris plant. One class is linearly separable from the other 2; the latter are NOT linearly separable from each other. 

Predicted attribute: class of iris plant. 

This is an exceedingly simple domain. 

This data differs from the data presented in Fishers article (identified by Steve Chadwick, spchadwick '@' espeedaz.net ). The 35th sample should be: 4.9,3.1,1.5,0.2,"Iris-setosa" where the error is in the fourth feature. The 38th sample: 4.9,3.6,1.4,0.1,"Iris-setosa" where the errors are in the second and third features.


Attribute Information:

1. sepal length in cm 
2. sepal width in cm 
3. petal length in cm 
4. petal width in cm 
5. class: 
-- Iris Setosa 
-- Iris Versicolour 
-- Iris Virginica

### Step 3. Assign it to a variable called iris

In [5]:
# url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
url = 'http://mlr.cs.umass.edu/ml/machine-learning-databases/iris/iris.data'
iris = pd.read_csv(url)

iris.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

### Step 4. Create columns for the dataset

In [6]:
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

iris.columns = ['sepal_length','sepal_width', 'petal_length', 'petal_width', 'class']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           4.9          3.0           1.4          0.2  Iris-setosa
1           4.7          3.2           1.3          0.2  Iris-setosa
2           4.6          3.1           1.5          0.2  Iris-setosa
3           5.0          3.6           1.4          0.2  Iris-setosa
4           5.4          3.9           1.7          0.4  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [7]:
pd.isnull(iris).sum()
# nice no missing value

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [8]:
iris.iloc[10:30,2:3] = np.nan
iris.head(20)

    sepal_length  sepal_width  petal_length  petal_width        class
0            4.9          3.0           1.4          0.2  Iris-setosa
1            4.7          3.2           1.3          0.2  Iris-setosa
2            4.6          3.1           1.5          0.2  Iris-setosa
3            5.0          3.6           1.4          0.2  Iris-setosa
4            5.4          3.9           1.7          0.4  Iris-setosa
5            4.6          3.4           1.4          0.3  Iris-setosa
6            5.0          3.4           1.5          0.2  Iris-setosa
7            4.4          2.9           1.4          0.2  Iris-setosa
8            4.9          3.1           1.5          0.1  Iris-setosa
9            5.4          3.7           1.5          0.2  Iris-setosa
10           4.8          3.4           NaN          0.2  Iris-setosa
11           4.8          3.0           NaN          0.1  Iris-setosa
12           4.3          3.0           NaN          0.1  Iris-setosa
13           5.8          4.0           NaN          0.2  Iris-setosa
14           5.7          4.4           NaN          0.4  Iris-setosa
15           5.4          3.9           NaN          0.4  Iris-setosa
16           5.1          3.5           NaN          0.3  Iris-setosa
17           5.7          3.8           NaN          0.3  Iris-setosa
18           5.1          3.8           NaN          0.3  Iris-setosa
19           5.4          3.4           NaN          0.2  Iris-setosa

### Step 7. Good, now lets substitute the NaN values to 1.0

In [9]:
iris.petal_length.fillna(1, inplace = True)

# Signature: iris.petal_length.fillna(value=None, method=None, axis=None, inplace=False, limit=None, 
#                                     downcast=None, **kwargs)
# Docstring:
# Fill NA/NaN values using the specified method

# Parameters
# ----------
# value : scalar, dict, Series, or DataFrame
#     Value to use to fill holes (e.g. 0), alternately a
#     dict/Series/DataFrame of values specifying which value to use for
#     each index (for a Series) or column (for a DataFrame). (values not
#     in the dict/Series/DataFrame will not be filled). This value cannot
#     be a list.
# method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
#     Method to use for filling holes in reindexed Series
#     pad / ffill: propagate last valid observation forward to next valid
#     backfill / bfill: use NEXT valid observation to fill gap
# axis : {0, 'index'}
# inplace : boolean, default False
#     If True, fill in place. Note: this will modify any
#     other views on this object, (e.g. a no-copy slice for a column in a
#     DataFrame).
# limit : int, default None
#     If method is specified, this is the maximum number of consecutive
#     NaN values to forward/backward fill. In other words, if there is
#     a gap with more than this number of consecutive NaNs, it will only
#     be partially filled. If method is not specified, this is the
#     maximum number of entries along the entire axis where NaNs will be
#     filled.
# downcast : dict, default is None
#     a dict of item->dtype of what to downcast if possible,
#     or the string 'infer' which will try to downcast to an appropriate
#     equal type (e.g. float64 to int64 if possible)

# See Also
# --------
# reindex, asfreq

# Returns
# -------
# filled : Series

iris

     sepal_length  sepal_width  petal_length  petal_width           class
0             4.9          3.0           1.4          0.2     Iris-setosa
1             4.7          3.2           1.3          0.2     Iris-setosa
2             4.6          3.1           1.5          0.2     Iris-setosa
3             5.0          3.6           1.4          0.2     Iris-setosa
4             5.4          3.9           1.7          0.4     Iris-setosa
5             4.6          3.4           1.4          0.3     Iris-setosa
6             5.0          3.4           1.5          0.2     Iris-setosa
7             4.4          2.9           1.4          0.2     Iris-setosa
8             4.9          3.1           1.5          0.1     Iris-setosa
9             5.4          3.7           1.5          0.2     Iris-setosa
10            4.8          3.4           1.0          0.2     Iris-setosa
11            4.8          3.0           1.0          0.1     Iris-setosa
12            4.3          3.0           1.0          0.1     Iris-setosa
13            5.8          4.0           1.0          0.2     Iris-setosa
14            5.7          4.4           1.0          0.4     Iris-setosa
15            5.4          3.9           1.0          0.4     Iris-setosa
16            5.1          3.5           1.0          0.3     Iris-setosa
17            5.7          3.8           1.0          0.3     Iris-setosa
18            5.1          3.8           1.0          0.3     Iris-setosa
19            5.4          3.4           1.0          0.2     Iris-setosa
20            5.1          3.7           1.0          0.4     Iris-setosa
21            4.6          3.6           1.0          0.2     Iris-setosa
22            5.1          3.3           1.0          0.5     Iris-setosa
23            4.8          3.4           1.0          0.2     Iris-setosa
24            5.0          3.0           1.0          0.2     Iris-setosa
25            5.0          3.4           1.0          0.4     Iris-setosa
26            5.2          3.5           1.0          0.2     Iris-setosa
27            5.2          3.4           1.0          0.2     Iris-setosa
28            4.7          3.2           1.0          0.2     Iris-setosa
29            4.8          3.1           1.0          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
119           6.9          3.2           5.7          2.3  Iris-virginica
120           5.6          2.8           4.9          2.0  Iris-virginica
121           7.7          2.8           6.7          2.0  Iris-virginica
122           6.3          2.7           4.9          1.8  Iris-virginica
123           6.7          3.3           5.7          2.1  Iris-virginica
124           7.2          3.2           6.0          1.8  Iris-virginica
125           6.2          2.8           4.8          1.8  Iris-virginica
126           6.1          3.0           4.9          1.8  Iris-virginica
127           6.4          2.8           5.6          2.1  Iris-virginica
128           7.2          3.0           5.8          1.6  Iris-virginica
129           7.4          2.8           6.1          1.9  Iris-virginica
130           7.9          3.8           6.4          2.0  Iris-virginica
131           6.4          2.8           5.6          2.2  Iris-virginica
132           6.3          2.8           5.1          1.5  Iris-virginica
133           6.1          2.6           5.6          1.4  Iris-virginica
134           7.7          3.0           6.1          2.3  Iris-virginica
135           6.3          3.4           5.6          2.4  Iris-virginica
136           6.4          3.1           5.5          1.8  Iris-virginica
137           6.0          3.0           4.8          1.8  Iris-virginica
138           6.9          3.1           5.4          2.1  Iris-virginica
139           6.7          3.1           5.6          2.4  Iris-virginica
140           6.9          3.1           5.1          2.3  Iris-virginica
141           5.8          2.7           5.1          1.9  Iris-virginica
142           6.8          3.2           5.9          2.3  Iris-virginica
143           6.7          3.3           5.7          2.5  Iris-virginica
144           6.7          3.0           5.2          2.3  Iris-virginica
145           6.3          2.5           5.0          1.9  Iris-virginica
146           6.5          3.0           5.2          2.0  Iris-virginica
147           6.2          3.4           5.4          2.3  Iris-virginica
148           5.9          3.0           5.1          1.8  Iris-virginica

[149 rows x 5 columns]

### Step 8. Now let's delete the column class

In [10]:
del iris['class']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           4.9          3.0           1.4          0.2
1           4.7          3.2           1.3          0.2
2           4.6          3.1           1.5          0.2
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

### Step 9.  Set the first 3 rows as NaN

In [11]:
iris.iloc[0:3 ,:] = np.nan
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           NaN          NaN           NaN          NaN
1           NaN          NaN           NaN          NaN
2           NaN          NaN           NaN          NaN
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4

### Step 10.  Delete the rows that have NaN

In [12]:
iris = iris.dropna(how='any')

# Signature: iris.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
# Docstring:
# Return object with labels on given axis omitted where alternately any
# or all of the data are missing

# Parameters
# ----------
# axis : {0 or 'index', 1 or 'columns'}, or tuple/list thereof
#     Pass tuple or list to drop on multiple axes
# how : {'any', 'all'}
#     * any : if any NA values are present, drop that label
#     * all : if all values are NA, drop that label
# thresh : int, default None
#     int value : require that many non-NA values
# subset : array-like
#     Labels along other axis to consider, e.g. if you are dropping rows
#     these would be a list of columns to include
# inplace : boolean, default False
#     If True, do operation inplace and return None.

# Returns
# -------
# dropped : DataFrame

iris.head()

   sepal_length  sepal_width  petal_length  petal_width
3           5.0          3.6           1.4          0.2
4           5.4          3.9           1.7          0.4
5           4.6          3.4           1.4          0.3
6           5.0          3.4           1.5          0.2
7           4.4          2.9           1.4          0.2

### Step 11. Reset the index so it begins with 0 again

In [13]:
iris = iris.reset_index(drop = True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.0          3.6           1.4          0.2
1           5.4          3.9           1.7          0.4
2           4.6          3.4           1.4          0.3
3           5.0          3.4           1.5          0.2
4           4.4          2.9           1.4          0.2

### BONUS: Create your own question and answer it.